Save/Vault offboarding
mstable/mStable-contracts pull request #275
Opened 2021-11-10 11:54 UTC by chrisjgf

## Changelog
- `unwrapAndSend` on `Unwrapper`. Upgradeable contract to unwrap mAsset -> bAsset/fAsset
- `redeemAndUnwrap` on `SavingsContract`. Redeems mAsset & uses `unwrapAndSend`
- `withdrawAndUnwrap` on `BoostedVault`. Withdraws from vault and uses `redeemAndUnwrap`
- `_reduceRaw` on `BoostedTokenWrapper`. Decrements user's raw balance without transferring token

2021-11-11 10:26 UTC, alsco77 requested changes
Functionality looks good, we have all the paths covered (vault -> imAsset && imAsset -> b/fAsset) and I think the immutable unwrapper and the arg for `_router` makes sense for future proofing.

Changes needed:
 - fix this broken test suite/CI
 - resolve comments
 - add some simple e2e tests for each of the paths (imAsset -> fAsset, imAsset -> bAsset, vault -> fAsset, vault -> bAsset). You could just make a new test file or use the unwrapper

2021-11-11 10:26 UTC, alsco77 commented on contracts/interfaces/IBoostedVaultWithLockup.sol
> +    // TODO add referrer overload?
Probably not necessary for the vault

2021-11-11 10:26 UTC, alsco77 commented on contracts/rewards/boosted-staking/BoostedTokenWrapper.sol
> +    function _reduceRaw(uint256 _amount) internal nonReentrant {
adding this second `nonReentrant` will cause any calls to `_withdrawRaw` to fail

2021-11-11 10:26 UTC, alsco77 commented on contracts/rewards/boosted-staking/BoostedVault.sol
> +        IERC20(stakingToken).approve(address(stakingToken), _amount);
Do we need to approve here? I think the savingscontract can just burn the tokens from msg.sender (which will be this staking contract account when called below)

2021-11-11 10:26 UTC, alsco77 commented on contracts/savings/SavingsContract.sol
> +    event Referral(address indexed referrer, address beneficiary);
Think we need to track the amount deposited here

2021-11-11 10:26 UTC, alsco77 commented on contracts/savings/peripheral/Unwrapper.sol
> +        bool _isBassetOut,
Only thing i see in this fn is that the integrator requires some knowledge about the mStable system to know whether this is true or false. Ideally would just pass the output addr

2021-11-11 10:26 UTC, alsco77 commented on contracts/savings/peripheral/Unwrapper.sol
> +        bool _isBassetOut,
Might be hard to do in an immutable and gas efficient way

2021-11-11 10:26 UTC, alsco77 commented on contracts/savings/peripheral/Unwrapper.sol
> +        bool _isBassetOut,
Maybe we can just have a view fn here that takes an mAsset addr (or imAsset), an output addr, and then returns a bool for `isBassetOut`. At least integration contracts can look this up off chain before sending the tx if they want

2021-11-25 13:30 UTC, alsco77 approved these changes

2021-12-15 13:13 UTC, doncesarts commented on test-fork/savings/sc21-upgrade.spec.ts
> +context("Unwrapper and Vault upgrades", () => {
@doncesarts  review  probably it should be a unit test

2022-02-01 12:17 UTC, naddison36 commented on contracts/rewards/boosted-staking/BoostedVault.sol
> +    ) external override updateReward(msg.sender) updateBoost(msg.sender) {
I've gone with `outputQuantity` as the return param

2022-02-01 12:17 UTC, naddison36 commented on contracts/savings/SavingsContract.sol
> +    ) external override returns (uint256 creditsBurned, uint256 massetReturned) {
I've gone with `outputQuantity` as the return param

2022-02-01 12:18 UTC, naddison36 commented on test-fork/savings/unwrapper.spec.ts
> +        const isCredit = true
I've added tests for when `isCredit` is false

2022-02-23 08:03 UTC, closed without merging